site_name: Value Set Workbench
theme: material
pages:
  - Home: index.md
  - Installation: installation.md
  - Custom OAuth2: custom_oauth.md
  #- User Guide: user_guide.md
  #- Admininstration: admininstration.md
  - Components: components.md
  - Research: research.md
  - Links: links.md

markdown_extensions:
  - markdown_include.include:
  - admonition
  - codehilite(linenums=true)

